version: "3"

services:
  app:
    container_name: music_app
    build: ./
    command: sh -c "python3 manage.py migrate &&
                    gunicorn --bind 0.0.0.0:8000 config.wsgi"
    restart: always
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - staticfiles:/usr/src/app/static
    ports:
      - "8000:8000"

  db:
    container_name: music_db
    image: postgres:latest
    restart: always
    expose:
      - ${POSTGRES_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  webserver:
    container_name: music_webserver
    image: nginx:latest
    restart: always
    expose:
      - 80
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - app
    volumes:
      - staticfiles:/static
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

volumes:
  staticfiles:
  db_data:
