# Generated by Django 4.1.7 on 2023-02-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(verbose_name='Дата выпуска'),
        ),
        migrations.AlterUniqueTogether(
            name='albumsong',
            unique_together={('album', 'song')},
        ),
    ]
